version: '3.8'

services:
  # 1. Frontend
  frontend:
    build: ./front/water-front
    container_name: water-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  # 2. Backend
  backend:
    build: ./back
    container_name: water-backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:secret@db:5432/waterdb?sslmode=disable
    depends_on:
      - db
    restart: always

  # 3. Database
  db:
    image: postgres:15-alpine
    container_name: water-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: waterdb
    volumes:
      - pg_data:/var/lib/postgresql/data

  # 4. Prometheus (Сборщик метрик)
  prometheus:
    image: prom/prometheus:latest
    container_name: water-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - backend

  # 5. Grafana (Визуализация)
  grafana:
    image: grafana/grafana:latest
    container_name: water-grafana
    ports:
      - "3001:3000" # Внимание: Внешний порт 3001
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Пароль администратора
    depends_on:
      - prometheus
      - db

volumes:
  pg_data: